---

- hosts: localhost
  tasks:
  - name: Fetch all solution subdirectories
    find:
      paths: ./
      file_type: directory
      use_regex: yes
      patterns: '^day.*'
    register: solution_directories

  - name: Test all Advent of Code 2022 solutions
    shell: |
      cd {{ item.path }} && pytest -vv
    with_items: "{{ solution_directories.files }}"
    register: test_results

  - name: Print test results
    debug:
      msg: "{{ item.stdout_lines }}"
    with_items: "{{ test_results.results }}"
