name: Path lister test
on: [push]
jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Perform tests
        run: |
          for dir in ./*; 			# For every item in the folder:
            do ( 
              if [ -d "$dir" ]; 			# If it is a directory:			
                then (
                  echo "$dir" &&  		# Print the path,
                  cd "$dir" && 			# Change directory into the path,
                  pipenv install && pipenv shell && pip3 install pytest pytest-watch
                  pytest -vv
                  echo. 					# Toss in a new line for readability.
                );
              fi
            ); 
          done
